name: Build C64 Program

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run compilation
      run: |
        mkdir -p out
        ls -la
        ls src
        pwd
        docker run --rm -v ${{ github.workspace }}:/app ghcr.io/amarcinkowski/super64setup src/main.asm -o out/main.prg

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: c64-program
        path: out/main.prg
